version: '2'
services:
  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - ./data_redis:/data

  web:
    build: .
    container_name: lpbc
    image: template_lpbc:latest
    working_dir: /local/app
    env_file:
      - .env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/local
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
