# Generated by Django 2.0.3 on 2018-04-04 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_descripcion', models.CharField(blank=True, max_length=255)),
                ('blog', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('code', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=255)),
                ('documento_identificativo', models.CharField(blank=True, max_length=255)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=255)),
                ('pais_nacionalidad', models.CharField(blank=True, max_length=255)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=255)),
                ('pais_residencia', models.CharField(blank=True, max_length=255)),
                ('domicilio', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('acreditacion_poderes', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion_social', models.CharField(blank=True, default='', max_length=100)),
                ('CIF', models.CharField(blank=True, default='', max_length=100)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_constitucion', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('forma_juridica', models.CharField(blank=True, default='', max_length=100)),
                ('registro', models.CharField(blank=True, default='', max_length=100)),
                ('numero_inscripciones', models.IntegerField()),
                ('poblacion', models.CharField(blank=True, default='', max_length=100)),
                ('provincia', models.CharField(blank=True, default='', max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('pais', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('mail', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('cliente', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionJuridicaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_particulares', models.CharField(blank=True, max_length=255)),
                ('persona_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.PersonaFisica')),
                ('persona_juridica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.PersonaJuridica')),
                ('tipo_relacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Relacion')),
            ],
        ),
    ]
