# Generated by Django 2.0.3 on 2018-06-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationuser',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='organizationuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
