# Generated by Django 2.0.3 on 2018-06-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180614_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='nif',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
