# Generated by Django 2.0.3 on 2018-06-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180626_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cliente',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
