# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lpbc', '0003_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_descripcion', models.CharField(blank=True, max_length=255)),
                ('blog', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=255)),
                ('documento_identificativo', models.CharField(blank=True, max_length=255)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=255)),
                ('pais_nacionalidad', models.CharField(blank=True, max_length=255)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=255)),
                ('pais_residencia', models.CharField(blank=True, max_length=255)),
                ('domicilio', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('acreditacion_poderes', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion_social', models.CharField(blank=True, default='', max_length=100)),
                ('CIF', models.CharField(blank=True, default='', max_length=100)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_constitucion', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('forma_juridica', models.CharField(blank=True, default='', max_length=100)),
                ('registro', models.CharField(blank=True, default='', max_length=100)),
                ('numero_inscripciones', models.IntegerField()),
                ('poblacion', models.CharField(blank=True, default='', max_length=100)),
                ('provincia', models.CharField(blank=True, default='', max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('pais', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionJuridicaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_particulares', models.CharField(blank=True, max_length=255)),
                ('persona_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lpbc.PersonaFisica')),
                ('persona_juridica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lpbc.PersonaJuridica')),
                ('tipo_relacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lpbc.Relacion')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='cliente',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
