# Generated by Django 2.0.3 on 2018-06-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('length', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion_social', models.CharField(blank=True, default='', max_length=100)),
                ('CIF', models.CharField(blank=True, default='', max_length=100)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_constitucion', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('forma_juridica', models.CharField(blank=True, default='', max_length=100)),
                ('registro', models.CharField(blank=True, default='', max_length=100)),
                ('numero_inscripciones', models.IntegerField()),
                ('poblacion', models.CharField(blank=True, default='', max_length=100)),
                ('provincia', models.CharField(blank=True, default='', max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('pais', models.CharField(blank=True, max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Project')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=255)),
                ('documento_identificativo', models.CharField(blank=True, max_length=255)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=255)),
                ('pais_nacionalidad', models.CharField(blank=True, max_length=255)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=255)),
                ('pais_residencia', models.CharField(blank=True, max_length=255)),
                ('domicilio', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('capital', models.BooleanField(default=False)),
                ('responsabilidad_publica', models.BooleanField(default=False)),
                ('controla_sociedad', models.BooleanField(default=False)),
                ('control', models.BooleanField(default=False)),
                ('relacion_negocios', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipLegalPhysical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_particulares', models.CharField(blank=True, max_length=255)),
                ('persona_fisica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.PhysicalPerson')),
                ('persona_juridica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.LegalPerson')),
                ('tipo_relacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Relationship')),
            ],
        ),
        migrations.CreateModel(
            name='SupportDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_justificacion', models.CharField(blank=True, max_length=255)),
                ('persona_fisica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.PhysicalPerson')),
                ('persona_juridica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.LegalPerson')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Project')),
            ],
        ),
    ]
