# Generated by Django 2.0.3 on 2018-05-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalperson',
            name='capital',
            field=models.BooleanField(default=False),
        ),
    ]
