# Generated by Django 2.0.3 on 2018-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_physicalperson_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalperson',
            name='control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='controla_sociedad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='relacion_negocios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='responsabilidad_publica',
            field=models.BooleanField(default=False),
        ),
    ]
