# Generated by Django 2.0.3 on 2018-07-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20180626_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalperson',
            old_name='documento_identificativo',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='domicilio',
            new_name='birthplace',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='lugar_nacimiento',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='fecha_caducidad',
            new_name='deliveryDate',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='capital',
            new_name='hasBussinesRelation',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='control',
            new_name='hasCapital',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='controla_sociedad',
            new_name='hasControl',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='relacion_negocios',
            new_name='hasPublicResponsability',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='responsabilidad_publica',
            new_name='hasSocietyControl',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='nacionalidad',
            new_name='identificationDocument',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='nombre_completo',
            new_name='nacionality',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='pais_nacionalidad',
            new_name='nacionalityCountry',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='pais_residencia',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='physicalperson',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='typePublicResponsability',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
