# Generated by Django 2.0.3 on 2018-05-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20180514_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalperson',
            name='acreditacion_poderes',
        ),
    ]
