# Generated by Django 2.0.3 on 2018-05-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('client', '0004_remove_physicalperson_acreditacion_poderes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='blog',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='document',
            name='persona_fisica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.PhysicalPerson'),
        ),
        migrations.AddField(
            model_name='document',
            name='persona_juridica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.LegalPerson'),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Project'),
        ),
    ]
