# Generated by Django 2.0.3 on 2018-07-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20180704_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalperson',
            name='typePublicResponsability',
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='isPublicResponsabilityOtherCountry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='publicResponsabilityCountries',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='relationPublicResponsability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='typeBussinesRelation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='typeControl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='physicalperson',
            name='typeSocietyControl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
