# Generated by Django 2.0.3 on 2018-07-09 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20180705_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportdoc',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.Document'),
            preserve_default=False,
        ),
    ]
