# Generated by Django 2.0.3 on 2018-06-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20180521_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportdoc',
            name='persona_fisica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.PhysicalPerson'),
        ),
        migrations.AlterField(
            model_name='supportdoc',
            name='persona_juridica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.LegalPerson'),
        ),
    ]
