# Generated by Django 2.0.3 on 2018-07-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20180709_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportdoc',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
